No Parameter Funtion

In [1]:
def Hello():
    print("Hello World")

In [2]:
Hello()

Hello World

Parameter Funtion

In [3]:
def Hello(user):
    print(f"Hello {user}")

In [4]:
Hello("Hujaifa")

Hello Hujaifa

Default Input Parameter

In [5]:
def Hello(user = "None"):
    print(f"Hello {user}")

In [6]:
Hello()

Hello None

Return

In [10]:
def adder(a,b):

    """
    Add Two Numbers
    """
    
    sum = a + b
    return sum

In [8]:
m = adder(10,30) * 5
print(m)

200

Help funtion

In [11]:
help(adder)

Help on function adder in module __main__:

adder(a, b)
    Add Two Numbers

In [12]:
help(print)

Help on built-in function print in module builtins:

print(*args, sep=' ', end='\n', file=None, flush=False)
    Prints the values to a stream, or to sys.stdout by default.

    sep
      string inserted between values, default a space.
    end
      string appended after the last value, default a newline.
    file
      a file-like object (stream); defaults to the current sys.stdout.
    flush
      whether to forcibly flush the stream.

Different Types of Argumrnts

In [14]:
def add(a,b,c):  # Positional Arguments
    print(f"{a},{b},{c}")

add(20,30,10)

20,30,10

In [15]:
def add(*args):  # Variable Sized Arguments
    print(args)
    for i in args:
        print(i)

add(20,30,10,50,60)

(20, 30, 10, 50, 60)
20
30
10
50
60

KeyWord Arguments

In [16]:
def add(a,b,c):  
    print(f"{a},{b},{c}")

add(b = 20,c = 30,a = 10)

10,20,30

Variable Sized KeyWord Arguments

In [ ]:
def add(**kwargs):
    print(kwargs)
    for k,v in kwargs.items():
        print(f"{k} : {v}")

add(a = 10,b = 30,c = 20)

{'a': 10, 'b': 30, 'c': 20}
a : 10
b : 30
c : 20

Return Type

In [2]:
def sum(a,b):
    ans = a + b
    return ans
m = sum(10,20) * 10
print(m)

300

Iterator

In [3]:
s = {10,20,30,40}
print(s[1])

TypeError: 'set' object is not subscriptable

In [8]:
s ={10,20,30,40,50}
s_itr = iter(s)
print(type(iter))
print(next(s_itr))
print(next(s_itr))
print(next(s_itr))

print("Using Loop: ")

for i in s:
    print(i)

<class 'builtin_function_or_method'>
50
20
40
Using Loop:
50
20
40
10
30

Generator

In [11]:
lst = [x for x in range(500)]

def data_loader(chunk_size,lst):
    for i in range(len(lst)):
        yield lst[i:i+chunk_size]

x = data_loader(5,lst)
print(x,type(x))
print(next(x))

<generator object data_loader at 0x000001803AA55120> <class 'generator'>
[0, 1, 2, 3, 4]

In [22]:
lst = [x for x in range(500)]

def loader(chunk_size,lst):
    for i in range(0,len(lst),chunk_size):
        yield lst[i : i + chunk_size]
x = loader(5,lst)
print(next(x))

[0, 1, 2, 3, 4]

Lambda Function

In [4]:
##Python lambda functions are small, single-expression anonymous functions created
#  without a name using the lambda keyword (Syntax: lambda arguments: expression) 
# that automatically return the computed result

import pandas as pd

df  = pd.DataFrame({'temperature (F) ': [32,212,98.6,68]})

df['temperature (C) '] = df['temperature (F) '].apply(lambda x: (x-32) * 5/9)
df

   temperature (F)   temperature (C)
0              32.0               0.0
1             212.0             100.0
2              98.6              37.0
3              68.0              20.0

In [7]:
import pandas as pd

df = pd.DataFrame({'A' : [1,2,3,4], 'B' : [5,6,7,8]})

df['A'] = df['A'].map(lambda x: x**0.5)
df

          A  B
0  1.000000  5
1  1.414214  6
2  1.732051  7
3  2.000000  8

In [8]:
import pandas as pd

df = pd.DataFrame({'total_spent' : [120,600,450,800]})

df['is_high_value'] = df['total_spent'].apply(lambda x : 1 if x>500 else 0)
df

   total_spent  is_high_value
0          120              0
1          600              1
2          450              0
3          800              1